// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHMhCXqpH20TDNTNUeSTlsAYdxjjBLt44',
    appId: '1:530052324208:web:ae33ceb93b95895275cdb5',
    messagingSenderId: '530052324208',
    projectId: 'app-2mint-recipes',
    authDomain: 'app-2mint-recipes.firebaseapp.com',
    storageBucket: 'app-2mint-recipes.appspot.com',
    measurementId: 'G-4LBKT6L6CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNc0WQsNvM9guXwQ1fTGryVrGepw7p1II',
    appId: '1:530052324208:android:e3a8203a5a4835af75cdb5',
    messagingSenderId: '530052324208',
    projectId: 'app-2mint-recipes',
    storageBucket: 'app-2mint-recipes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Ye5ePns2MXPeL3MOBOxmzoVhXTviZUM',
    appId: '1:530052324208:ios:bee574bba62f4d8475cdb5',
    messagingSenderId: '530052324208',
    projectId: 'app-2mint-recipes',
    storageBucket: 'app-2mint-recipes.appspot.com',
    iosClientId: '530052324208-oiqcep8hiqv967vnojbjs202dt5f181i.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirst',
  );
}
